In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

df = pd.read_csv("../data/raw/apache1_dataset.csv")

print("Shape:", df.shape)

df.head()

Shape: (104557, 67)

,ID,UHID,IPNumber,ICUChartDate,Age,Temperature,MeanArterialPressure,HeartRate,RespiratoryRate,FiO2,pO2,pCO2,ArterialpH,Sodium,UrineOutput,Creatinine,Urea,BSL,Albumin,Bilirubin,Hematocrit,WBC,IsGCSNotAvailable,GCSEyes,GCSVerbal,GCSMotor,MecanicalVentilation,CRF,Lymphoma,Cirrhosis,Leukemia,HepaticFailure,Immunosuppression,MetastaticCarcinoma,AIDS,PreICULengthOfStay,DiagnosisType,Origin,EmergencySurgery,Readmission,Thrombolysis,RespiratoryQuotient,AtmosphericPressure,SystemValue,DiagnosisValue,CreatedBy,CreatedDate,UpdatedBy,UpdatedDate,DOB,Gender,AdmittingDoctor,Ward,ApacheivScore,ApsScore,EstimatedMortalityRate,EstimatedLengthOfStay,AdmissionDate,UNIT_ID,CREATEDON,RNK,APACHE_WARD,CUSTOMERSTATUS,LOCATIONID,LOCATION,DISCHARGEDATE,PERIOD_WID
0,4978,APD1.0012042887,DELIP573294,1/23/26 0:00,83,36.9,103.00,100.0,20.0,40.0,97.7,43.0,7.42,146.0,1655.000000,0.800000,14.630000,150.000000,22.500000,0.400000,34.00000,7.840000,0,4,4,5,a,0,0,0,0,0,0,0,0,2,1,1,0,0,0,0.0,760.0,Miscellaneous,Diagnosis,12,1/24/26 15:43,NaN,NaN,12-07-2042 00:00,Female,ALOK AGARWAL,NaN,43,26,37.0,3.7,1/21/26 0:00,4,2026-02-10T01:36:11.1029417Z,1,6th Flr T2,ALIVE,10701.0,Delhi - Sarita Vihar,10:00.4,20260123
1,10124,AHS.0000417587,AHSIP101940,02-04-2026 00:00,44,36.0,84.00,78.0,20.0,30.0,87.0,35.0,7.38,136.0,69.726667,72.270061,74.813455,77.356848,79.900242,82.443636,84.98703,87.530424,0,4,5,6,a,0,0,0,0,0,0,1,0,10,2,0,0,0,0,0.0,760.0,Respiratory,Other,30,02-05-2026 17:54,NaN,NaN,11-05-1981 00:00,Male,Pradeep Hosamani,NaN,28,17,6.4,2.0,02-03-2026 00:00,8,2026-02-10T01:38:57.3490126Z,1,GENERAL WARD LEVEL 5,ALIVE,10391.0,Apollo hospital Sheshadripuram,NaN,20260204
2,36594,AHLG.000582499,AHLGIP68174,02-03-2026 00:00,75,36.7,73.26,104.0,20.0,30.0,141.0,26.0,7.45,138.0,2140.000000,2.400000,6.940000,149.000000,21.000000,0.900000,29.70000,11160.000000,0,2,1,3,b,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0.0,760.0,Sepsis,Unknown,91,02-04-2026 12:40,NaN,NaN,2/28/51 0:00,Male,SSD GROUP Siddharth Goswami Deepom Sarmah Swar...,NaN,77,60,36.2,6.1,02-02-2026 00:00,1,2026-02-10T01:33:13.9669818Z,1,NEURO ICU,ALIVE,17001.0,Assam Hospitals Limited – Guwahati,NaN,20260203
3,4815,ANM1.0001123066,ANMIP185974,1/19/26 0:00,43,37.0,77.00,110.0,16.0,40.0,196.0,34.1,7.40,146.0,660.000000,1.100000,9.930000,110.000000,40.000000,6.090000,27.00000,11.830000,0,4,1,3,b,0,0,0,0,0,0,0,0,1,2,2,0,0,0,0.0,760.0,Digestive,Liver Transplant,17,1/22/26 12:43,NaN,NaN,10/19/82 0:00,Male,HPB surgery and liver transplant,NaN,53,53,2.6,3.8,1/19/26 0:00,5,2026-02-10T01:38:05.9903312Z,1,D WARD,DEAD,10551.0,Navi Mumbai,NaN,20260119
4,10027,AHS.0000416624,AHSIP101703,1/25/26 0:00,51,36.0,98.00,96.0,20.0,30.0,178.0,36.0,7.32,131.0,1620.000000,0.700000,23.000000,135.000000,43.000000,2.100000,45.00000,14000.000000,0,4,4,6,a,0,0,0,0,0,0,0,0,3,1,3,0,0,0,0.0,760.0,Neurologic,Intracerebral Hemorrhage,30,1/28/26 11:19,NaN,NaN,7/20/74 0:00,Male,Agadi J B,NaN,31,26,10.5,3.2,1/25/26 0:00,8,2026-02-10T01:38:57.3490126Z,1,EMERGENCY,ALIVE,10391.0,Apollo hospital Sheshadripuram,01:18.2,20260125

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104557 entries, 0 to 104556
Data columns (total 67 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   ID                      104557 non-null  int64
 1   UHID                    104557 non-null  object
 2   IPNumber                104557 non-null  object
 3   ICUChartDate            104557 non-null  object
 4   Age                     104557 non-null  int64
 5   Temperature             104557 non-null  float64
 6   MeanArterialPressure    104557 non-null  float64
 7   HeartRate               104557 non-null  float64
 8   RespiratoryRate         104557 non-null  float64
 9   FiO2                    104557 non-null  float64
 10  pO2                     104557 non-null  float64
 11  pCO2                    104557 non-null  float64
 12  ArterialpH              104557 non-null  float64
 13  Sodium                  104557 non-null  float64
 14  UrineOutput             104557 non-null  float64
 15  Creatinine              104557 non-null  float64
 16  Urea                    104557 non-null  float64
 17  BSL                     104557 non-null  float64
 18  Albumin                 104557 non-null  float64
 19  Bilirubin               104557 non-null  float64
 20  Hematocrit              104557 non-null  float64
 21  WBC                     104557 non-null  float64
 22  IsGCSNotAvailable       104557 non-null  int64
 23  GCSEyes                 104557 non-null  int64
 24  GCSVerbal               104557 non-null  int64
 25  GCSMotor                104557 non-null  int64
 26  MecanicalVentilation    104557 non-null  object
 27  CRF                     104557 non-null  int64
 28  Lymphoma                104557 non-null  int64
 29  Cirrhosis               104557 non-null  int64
 30  Leukemia                104557 non-null  int64
 31  HepaticFailure          104557 non-null  int64
 32  Immunosuppression       104557 non-null  int64
 33  MetastaticCarcinoma     104557 non-null  int64
 34  AIDS                    104557 non-null  int64
 35  PreICULengthOfStay      104557 non-null  int64
 36  DiagnosisType           104557 non-null  int64
 37  Origin                  104557 non-null  int64
 38  EmergencySurgery        104557 non-null  int64
 39  Readmission             104557 non-null  int64
 40  Thrombolysis            104557 non-null  int64
 41  RespiratoryQuotient     104557 non-null  float64
 42  AtmosphericPressure     104557 non-null  float64
 43  SystemValue             104557 non-null  object
 44  DiagnosisValue          104557 non-null  object
 45  CreatedBy               104557 non-null  int64
 46  CreatedDate             104557 non-null  object
 47  UpdatedBy               0 non-null       float64
 48  UpdatedDate             0 non-null       float64
 49  DOB                     104557 non-null  object
 50  Gender                  104557 non-null  object
 51  AdmittingDoctor         104557 non-null  object
 52  Ward                    0 non-null       float64
 53  ApacheivScore           104557 non-null  int64
 54  ApsScore                104557 non-null  int64
 55  EstimatedMortalityRate  104557 non-null  float64
 56  EstimatedLengthOfStay   104557 non-null  float64
 57  AdmissionDate           104557 non-null  object
 58  UNIT_ID                 104557 non-null  int64
 59  CREATEDON               104557 non-null  object
 60  RNK                     104557 non-null  int64
 61  APACHE_WARD             99095 non-null   object
 62  CUSTOMERSTATUS          103599 non-null  object
 63  LOCATIONID              103594 non-null  float64
 64  LOCATION                103594 non-null  object
 65  DISCHARGEDATE           92581 non-null   object
 66  PERIOD_WID              104557 non-null  int64
dtypes: float64(25), int64(26), object(16)
memory usage: 53.4+ MB

In [3]:
df.columns.tolist()

['ID',
 'UHID',
 'IPNumber',
 'ICUChartDate',
 'Age',
 'Temperature',
 'MeanArterialPressure',
 'HeartRate',
 'RespiratoryRate',
 'FiO2',
 'pO2',
 'pCO2',
 'ArterialpH',
 'Sodium',
 'UrineOutput',
 'Creatinine',
 'Urea',
 'BSL',
 'Albumin',
 'Bilirubin',
 'Hematocrit',
 'WBC',
 'IsGCSNotAvailable',
 'GCSEyes',
 'GCSVerbal',
 'GCSMotor',
 'MecanicalVentilation',
 'CRF',
 'Lymphoma',
 'Cirrhosis',
 'Leukemia',
 'HepaticFailure',
 'Immunosuppression',
 'MetastaticCarcinoma',
 'AIDS',
 'PreICULengthOfStay',
 'DiagnosisType',
 'Origin',
 'EmergencySurgery',
 'Readmission',
 'Thrombolysis',
 'RespiratoryQuotient',
 'AtmosphericPressure',
 'SystemValue',
 'DiagnosisValue',
 'CreatedBy',
 'CreatedDate',
 'UpdatedBy',
 'UpdatedDate',
 'DOB',
 'Gender',
 'AdmittingDoctor',
 'Ward',
 'ApacheivScore',
 'ApsScore',
 'EstimatedMortalityRate',
 'EstimatedLengthOfStay',
 'AdmissionDate',
 'UNIT_ID',
 'CREATEDON',
 'RNK',
 'APACHE_WARD',
 'CUSTOMERSTATUS',
 'LOCATIONID',
 'LOCATION',
 'DISCHARGEDATE',
 'PERIOD_WID']

In [4]:
df.isnull().sum().sort_values(ascending=False)

UpdatedDate       104557
UpdatedBy         104557
Ward              104557
DISCHARGEDATE      11976
APACHE_WARD         5462
                   ...
Lymphoma               0
Cirrhosis              0
Leukemia               0
HepaticFailure         0
PERIOD_WID             0
Length: 67, dtype: int64

In [5]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ID,104557.0,NaN,NaN,NaN,15229.73535,12141.834653,1.0,3832.0,12598.0,25697.0,40907.0
UHID,104557,94852,AB01.0000094379,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IPNumber,104557,104557,DELIP573294,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ICUChartDate,104557,1240,10/14/25 0:00,154,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,104557.0,NaN,NaN,NaN,60.505542,16.020508,16.0,51.0,63.0,72.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...
CUSTOMERSTATUS,103599,5,ALIVE,91673,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LOCATIONID,103594.0,NaN,NaN,NaN,11051.931193,1687.501367,10101.0,10201.0,10351.0,10801.0,50501.0
LOCATION,103594,43,Hyderabad - Jubilee Hills,15602,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DISCHARGEDATE,92581,26484,20:01.0,288,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PERIOD_WID,104557.0,NaN,NaN,NaN,20240782.297646,10441.047656,20220803.0,20230807.0,20240914.0,20250531.0,20260209.0